<?php
/**
* Displays a form to edit the bank account information
* for the selected saved payment method.
*
* @author      Century Business Solutions <support@centurybizsolutions.com>
* @copyright   Copyright (c) 2020 Century Business Solutions  (www.centurybizsolutions.com)
*/
$payment = $block->getCustomerPaymentMethod();
?>
<form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getUrl('ebizcharge/ach/updateaction', ['_secure' => true]); ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields'); ?>">
    
    <?php echo $block->getBlockHtml('formkey'); ?>
	<input type="hidden" name="cid" value="<?php echo $block->getEbzcCustId(); ?>" />
	<input type="hidden" name="mid" value="<?php echo $block->getEbzcMethodId(); ?>" />
	<input type="hidden" name="ach_method_name" value="<?php echo $payment->MethodName; ?>" />

	<fieldset class="fieldset items">
		<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Payment Information'); ?></span></legend><br>
		<div class="field required">
			<label class="label" for="ach_holder"><span><?php /* @escapeNotVerified */ echo __('Account Holder'); ?></span></label>
			<input type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Account Holder'); ?>" name="ach_holder" id="ach_holder" value="<?php if (isset($payment->AccountHolderName)) {echo $payment->AccountHolderName;} ?>" data-input="ach_holder" autocomplete="off" data-validate="{'required-entry':true}" />
		</div>
		<div class="field required">
			<label for="cc_type" class="label">
				<span><?php echo $block->escapeHtml(__('Account Type')); ?></span>
			</label>
			<select id="cc_type"
				data-mage-init='{ 
					"creditCardType":{"creditCardTypeContainer":"#cc_type_ss_div"}
				}' name="ach_type" data-validate="{'required-entry':true}" class="select">
				<option value=""><?php echo $block->escapeHtml(__('--Please Select--')); ?></option>
                <option  value="checking" <?php if(trim($payment->AccountType)=='checking')  echo 'selected'; ?> >Checking </option>
               <option <?php if(trim($payment->AccountType) == 'savings' )  echo 'selected'; ?>  value="savings">Savings </option>
			</select>
		</div>
		<div class="field required">
			<label for="ach_number" class="label">
				<span><?php echo $block->escapeHtml(__('Account Number')); ?></span>
			</label>
			<input type="text" id="ach_number" name="ach_number" readonly title="<?php echo $block->escapeHtml(__('AccountNumber')); ?>" class="input-text"
                   minlength="9" maxlength="14" value="<?php if (isset($payment->Account)) {echo $payment->Account;} ?>"
                   data-validate="{'required-entry':true}"/>
		</div>
		<div class="field required">
			<label for="cc_exp_month" class="label">
				<span><?php echo $block->escapeHtml(__('Routing Number')); ?></span>
			</label>
			 <div><input type="text" id="ach_route" name="ach_route" readonly minlength="9" maxlength="9"
                         title="<?php echo $block->escapeHtml(__('Routing No')); ?>" class="input-text"
                         value="<?php if (isset($payment->Routing)) {echo $payment->Routing;} ?>" />
		</div>

        <div class="field" style="margin-top: 20px">
            <input type="checkbox" id="default" name="default" value="1" class="checkbox" <?php echo $payment->SecondarySort == 0 ? 'checked' : '';?>>
            <label class="label" for="default">
                <span style="font-weight: 600"><?php echo $block->escapeHtml(__('Make this my default bank account.')); ?></span>
            </label>
        </div>
	</fieldset>
	
    <div class="actions-toolbar">
        <div class="primary">
            <a href="<?php echo $block->getUrl('ebizcharge/ach/listaction'); ?>">
            	<button type="button" title="<?php /* @escapeNotVerified */ echo __('Cancel'); ?>" style="font-size: 1.8rem; line-height: 2.2rem; padding: 14px 17px;">
                	<span><?php /* @escapeNotVerified */ echo __('Cancel'); ?></span>
            	</button>
            </a>
            <button type="submit" class="action primary" title="<?php /* @escapeNotVerified */ echo __('Update Bank Account'); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Update Bank Account'); ?></span>
            </button>
        </div>
    </div>
		
</form>
	
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson(); ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId(); ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true); ?>
            }
        }
    }
</script>