<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

?>
<div class="product-add-form">
    <form data-product-sku="<?php echo $block->escapeHtmlAttr($_product->getSku()) ?>"
          action="<?php echo $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()) :?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php echo (int)$_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?php echo (int)$block->getRequest()->getParam('id') ?>" />
        <?php echo $block->getBlockHtml('formkey') ?>
        <?php echo $block->getChildHtml('form_top') ?>

		<!-- Start Recurring -->
		<?= $block->getChildHtml('ebizcharge.recurring.form'); ?>
		<!-- End Recurring -->

        <?php if (!$block->hasOptions()) :?>
            <?php echo $block->getChildHtml('product_info_form_content') ?>
        <?php else :?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') :?>
                <?php echo $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') :?>
            <?php echo $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php echo $block->getChildHtml('form_bottom') ?>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?php echo $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig":  <?php echo $block->getJsonConfig() ?>
            }
        }
    }
</script>
