<?php
/**
 * If there are saved payment methods, this will display a list of all of them.
 * If there are no saved payment methods, this will display a message with a
 * button to add a new payment method.
 *
 * @author      Century Business Solutions <support@centurybizsolutions.com>
 * @copyright   Copyright (c) 2020 Century Business Solutions  (www.centurybizsolutions.com)
 */
$paymentCards = $block->getPaymentMethods();
$achStatus = $block->getAchStatus();


$fullUrl = $block->getRequest()->getUriString();
$baseUrl = $block->getBaseUrl();
$urlArray = explode($baseUrl, $fullUrl);
$urlCurrent = 'ebizcharge/cards/listaction/';

if ($urlArray[1] == $urlCurrent)
    $buttonClass = "disabled";
else
    $buttonClass = "";
?>
<style>
    .tablinks {
        all: initial;
        background-image: none;
        background: #fff;
        color: #ccc;
        cursor: pointer;
        display: inline-block;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-weight: 600;
        margin: 0;
        padding: 7px 15px;
        font-size: 1.4rem;
        line-height: 1.6rem;
        box-sizing: border-box;
        vertical-align: middle;
        pointer-events: none;
        cursor: pointer;
        border-bottom: 4px solid #f00;

    }

    .tablinksNotSelect {
        all: initial;
        background-image: none;
        background: #fff;
        color: #333333;
        border: 0px;
        cursor: pointer;
        display: inline-block;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-weight: 600;
        margin: 0;
        padding: 7px 15px;
        font-size: 1.4rem;
        line-height: 1.6rem;
        box-sizing: border-box;
        vertical-align: middle;
    }

    .tablinksNotSelect:hover {
        border: 0px;
        background-image: none;
        background: #fff;
        color: #333333;

        display: inline-block;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-weight: 600;
        margin: 0;
        padding: 7px 15px;
        font-size: 1.4rem;
        line-height: 1.6rem;
        box-sizing: border-box;
        vertical-align: middle;
        border-bottom: 4px solid #f00;
    }
</style>

<div class="table-wrapper my-credit-cards">
    <div class="tab">
        <div class="tablinks">Stored Cards</div>
        <?php if ($achStatus == 1) { ?>

            <div class="tablinksNotSelect"
                 onclick="openPage('<?php echo $block->escapeUrl($block->getUrl('ebizcharge/ach/listaction/')); ?>')">
                Stored Bank Accounts
            </div>
        <?php } ?>
    </div>
    <br>
    <div class="actions-toolbar">
        <div class="primary">
            <!--<a href="<?php echo $block->escapeUrl($block->getBackUrl()); ?>">
        	<button type="button" title="<?php /* @escapeNotVerified */ echo __('Back'); ?>">
            	<span><?php /* @escapeNotVerified */ echo __('Back'); ?></span>
        	</button>
        </a>-->
            <a href="<?php echo $this->getUrl('ebizcharge/cards/addaction', ['_secure' => true]); ?>">
        	<button type="button" class="action primary" title="<?php /* @escapeNotVerified */ echo __('Add New Card'); ?>">
            	<span><?php /* @escapeNotVerified */ echo __('Add New Credit Card'); ?></span>
                </button>
            </a>
        </div>
    </div>
    <?php if ($paymentCards != NULL): ?>
        <table class="data table">
            <caption class="table-caption"><?php echo __('My Credit Cards'); ?></caption>
            <thead>
            <tr>
                <th><?php echo __('Cardholder'); ?></th>
                <th><?php echo __('Card Type & Number'); ?></th>
                <th><?php echo __('Default'); ?></th>
                <th><div align="center"><?php echo __('Expiration Date'); ?></div></th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($paymentCards as $payment) {
                if ($payment->MethodType != 'check') {
                    $custID = $block->getMageCustId();

                    if($block->checkPaymentMethodStatus((int)$custID, $payment->MethodID)) {
                        $alertDelete = "Are you sure you want to delete this payment method? This method is associated with your recurring subscription. If you delete this method it will suspend your subscription";
                    } else {
                        $alertDelete = "Are you sure you want to delete this payment method?";
                    }
                        ?>

                    <tr>
                        <td><?php echo $payment->MethodName; ?></td>
                        <td>
                            <?php if (!empty($payment->CardType) && !empty($image = $block->getCCTypeImage($payment->CardType))) { ?>
                                <img style="vertical-align: middle; width: 45px"
                                     src="<?php echo $this->getViewFileUrl('Ebizcharge_Ebizcharge::images/' . $image); ?>"/>
                            <?php }
                            echo $payment->CardNumber; ?>
                        </td>
                        <td><?php echo (isset($payment->SecondarySort) && $payment->SecondarySort == 0) ? 'Yes' : 'No'; ?></td>
                        <td>
                            <div align="center"><?php echo $payment->CardExpiration; ?></div>
                        </td>
                        <td class="col actions">
                            <a href="<?php echo $this->getUrl('ebizcharge/cards/editaction', ['_secure' => true,
                                'cid' => $this->getEbzcCustId(),
                                'mid' => $payment->MethodID,
                                'method' => urlencode($payment->MethodName)]); ?>">
                                <?php echo __('Edit'); ?>
                            </a>
                            <form class="form" method="post"
                                  action="<?php echo $block->escapeUrl($block->getUrl('ebizcharge/cards/deleteaction')); ?>">
                                <?php echo $block->getBlockHtml('formkey'); ?>
                                <input name="cid" value="<?php echo $block->getEbzcCustId(); ?>" type="hidden"/>
                                <input name="mid" value="<?php echo $payment->MethodID; ?>" type="hidden"/>
                                <input name="method" value="<?php echo urlencode($payment->MethodName); ?>"
                                       type="hidden"/>
                                <input name="cust_id" value="<?php echo $block->getMageCustId(); ?>" type="hidden"/>
                                <button type="submit" class="action delete" data-mage-init='{
                                "Ebizcharge_Ebizcharge/js/deleteWidget":{
									"type": "popup",
									"modalClass": "my-credit-cards-popup",
									"toggleEvent": "click",
									"title": "<?php echo $block->escapeHtml(__('Delete')) ?>",
                                    "content": "<?php echo $alertDelete; ?>?"
                                }
                            }'>
                                    <span><?php echo $block->escapeHtml(__('Delete')) ?></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                <?php }
            }
            ?>
            </tbody>
        </table>

    <?php else: ?>
        <div style="margin-top: 15px" class="message info empty"><span><?php echo __('You have no saved cards.'); ?></span></div>
    <?php endif ?>
</div>

<script type="text/javascript">
    function openPage(url) {
        if (url != "") {
            window.location = url;
        }
    }
</script>
